/**
 * Statische Liste der WM-2026-Teilnehmer (48 Teams).
 * Stand: nach den Playoffs vom März 2026 — das Feld ist komplett.
 * (Italien, Dänemark, Polen und Serbien sind NICHT qualifiziert.)
 * Verwendet im Weltmeister-Picker und in der Admin-Spielanlage.
 */
export const WM2026_TEAMS: { name: string; flag: string }[] = [
  { name: "Ägypten", flag: "🇪🇬" },
  { name: "Algerien", flag: "🇩🇿" },
  { name: "Argentinien", flag: "🇦🇷" },
  { name: "Australien", flag: "🇦🇺" },
  { name: "Belgien", flag: "🇧🇪" },
  { name: "Bosnien-Herzegowina", flag: "🇧🇦" },
  { name: "Brasilien", flag: "🇧🇷" },
  { name: "Curaçao", flag: "🇨🇼" },
  { name: "Deutschland", flag: "🇩🇪" },
  { name: "DR Kongo", flag: "🇨🇩" },
  { name: "Ecuador", flag: "🇪🇨" },
  { name: "Elfenbeinküste", flag: "🇨🇮" },
  { name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Frankreich", flag: "🇫🇷" },
  { name: "Ghana", flag: "🇬🇭" },
  { name: "Haiti", flag: "🇭🇹" },
  { name: "Irak", flag: "🇮🇶" },
  { name: "Iran", flag: "🇮🇷" },
  { name: "Japan", flag: "🇯🇵" },
  { name: "Jordanien", flag: "🇯🇴" },
  { name: "Kanada", flag: "🇨🇦" },
  { name: "Kap Verde", flag: "🇨🇻" },
  { name: "Katar", flag: "🇶🇦" },
  { name: "Kolumbien", flag: "🇨🇴" },
  { name: "Kroatien", flag: "🇭🇷" },
  { name: "Marokko", flag: "🇲🇦" },
  { name: "Mexiko", flag: "🇲🇽" },
  { name: "Neuseeland", flag: "🇳🇿" },
  { name: "Niederlande", flag: "🇳🇱" },
  { name: "Norwegen", flag: "🇳🇴" },
  { name: "Österreich", flag: "🇦🇹" },
  { name: "Panama", flag: "🇵🇦" },
  { name: "Paraguay", flag: "🇵🇾" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Saudi-Arabien", flag: "🇸🇦" },
  { name: "Schottland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { name: "Schweden", flag: "🇸🇪" },
  { name: "Schweiz", flag: "🇨🇭" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Spanien", flag: "🇪🇸" },
  { name: "Südafrika", flag: "🇿🇦" },
  { name: "Südkorea", flag: "🇰🇷" },
  { name: "Tschechien", flag: "🇨🇿" },
  { name: "Tunesien", flag: "🇹🇳" },
  { name: "Türkei", flag: "🇹🇷" },
  { name: "Uruguay", flag: "🇺🇾" },
  { name: "USA", flag: "🇺🇸" },
  { name: "Usbekistan", flag: "🇺🇿" },
];
